// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUserConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateUserConfig'](arg1, arg2, arg3);
}

export function DeleteWorkflow(arg1) {
  return window['go']['main']['App']['DeleteWorkflow'](arg1);
}

export function GetMonthList(arg1, arg2) {
  return window['go']['main']['App']['GetMonthList'](arg1, arg2);
}

export function GetUserConfig() {
  return window['go']['main']['App']['GetUserConfig']();
}

export function GetWorkLog(arg1) {
  return window['go']['main']['App']['GetWorkLog'](arg1);
}

export function GetWorkLogTypes() {
  return window['go']['main']['App']['GetWorkLogTypes']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InvalidateApiKey(arg1) {
  return window['go']['main']['App']['InvalidateApiKey'](arg1);
}

export function PostWorkLog(arg1, arg2) {
  return window['go']['main']['App']['PostWorkLog'](arg1, arg2);
}

export function VerifyApiKey(arg1) {
  return window['go']['main']['App']['VerifyApiKey'](arg1);
}
