// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appstore} from '../models';
import {worklog} from '../models';

export function CreateUserConfig(arg1:string,arg2:string,arg3:string):Promise<appstore.UserConfig>;

export function GetMonthList(arg1:number,arg2:number):Promise<Array<worklog.WorkDay>>;

export function GetUserConfig():Promise<appstore.UserConfig>;

export function Greet(arg1:string):Promise<string>;

export function VerifyApiKey(arg1:string):Promise<boolean>;
