// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appstore} from '../models';
import {worklog} from '../models';
import {main} from '../models';

export function CreateUserConfig(arg1:string,arg2:string,arg3:string):Promise<appstore.UserConfig>;

export function DeleteWorkflow(arg1:number):Promise<boolean>;

export function GetMonthList(arg1:number,arg2:number):Promise<Array<worklog.WorkDay>>;

export function GetUserConfig():Promise<appstore.UserConfig>;

export function GetWorkLog(arg1:number):Promise<Array<worklog.WorkLogResult>>;

export function GetWorkLogTypes():Promise<Array<worklog.WorkLogAttr>>;

export function Greet(arg1:string):Promise<string>;

export function InvalidateApiKey(arg1:boolean):Promise<void>;

export function PostWorkLog(arg1:Array<main.PostWorkLog>,arg2:number):Promise<void>;

export function VerifyApiKey(arg1:string):Promise<boolean>;
